### PR TITLE
Add motonuko to Contributors.md and SE-class-2023

### PR DESCRIPTION
**Pull request by motonuko**
## Description
- Add my name and github id to `Contributors.md`
- Add my name and github id to `SE-class-2023`

Note:
- `oto10`'s line is copied and duplicated in `SE-class-2023`. My name is  similar to him, so please don't delete my line if you clean up the file later.
- I didn't use student id, but use github id in `Contributors.md` as you said in the class.

### CODE REVIEW

**Review by raux — COMMENTED** [review]
Can you please clean up the spaces for me to approve. For some reason I cannot resolve the error.

**Comment by raux** [comment]
Hi Okuno-san,

Can you delete this PR, update your repo, and then send me another PR?

Raula

**Comment by raux** [comment]
I added your name so closing the PR

**Comment by motonuko** [comment]
I'm for the inconvenience caused.  I just realized the problem was caused by unchecking "Allow edits by maintainers".

**Pull request closed without merging**
